//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fuel()
        {
            this.TravelWarrant = new HashSet<TravelWarrant>();
        }
    
        public int IDFuel { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual City City { get; set; }
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelWarrant> TravelWarrant { get; set; }
    }
}
