//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.TravelWarrant = new HashSet<TravelWarrant>();
        }
    
        public int IDRoute { get; set; }
        public Nullable<int> TimeHours { get; set; }
        public Nullable<int> CityA { get; set; }
        public Nullable<int> CityB { get; set; }
        public Nullable<int> Kilometers { get; set; }
        public Nullable<int> AvgSpeed { get; set; }
        public Nullable<int> FuelUsed { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelWarrant> TravelWarrant { get; set; }
    }
}
