//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelWarrant
    {
        public int IDTravelWarrant { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<int> TravelWarrantTypeID { get; set; }
        public Nullable<int> FuelID { get; set; }
        public Nullable<int> RouteID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Fuel Fuel { get; set; }
        public virtual Route Route { get; set; }
        public virtual TravelWarrantType TravelWarrantType { get; set; }
    }
}
